### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by arxpoetica**

### CODE REVIEW

**Comment by arxpoetica** [comment]
Just trying to get things up to speed a bit, particularly with some Svelte changes

**Comment by Rich-Harris** [comment]
Thanks — do you need me to cut a new release? It should always install the latest 1.x version of Svelte, as things stand

**Comment by arxpoetica** [comment]
Maybe I'm not understanding you. How would it always install the latest 1.x if it's hardcoded in `package.json`?

image

**Comment by Rich-Harris** [comment]
It's not pinned — `^1.11.2` means 'the latest version that's higher than 1.11.2, but lower than 2.0.0'. If you trashed your `node_modules` folder and reinstalled, you would get the latest version. See https://runkit.com/rich/58c96de90cbc050014063057

**Comment by arxpoetica** [comment]
ahhhh...

closing then since this is not relevant ;) my bad.

**Comment by arxpoetica** [comment]
Future note for anyone else trying to figure this out, you also need to delete `yarn.lock`

**Pull request merged**
