### PR TITLE
Explained how to write the entry point code

### PR DESCRIPTION
**Pull request by sgurukrupa**
When using the 'iife' value for the 'format' option, it may not be evident how to write the entry point code. We need to export the function / object where Svelte's components are used / called.

### CODE REVIEW

**Comment by sgurukrupa** [comment]
This full example will be helpful for newbies like me :)

**Comment by sgurukrupa** [comment]
Didn't figure out what closing a pull request meant. Now I do :)

**Comment by PaulBGD** [comment]
Seems more complex than it needs to be, since all you need to call is new Combobox()

**Comment by sgurukrupa** [comment]
Where would you add new ComboBox()? Is it in main.js or in the web page that includes the bundle.js?

**Comment by PaulBGD** [comment]
You're exporting app so that you can call `app.start`, but why not just remove all of that and export the Combobox, then create a new instance of that?

**Pull request closed without merging**
